### ISSUE TITLE
Error with "hostonlyif", "create" on VBoxManage

### ISSUE THREAD

**Issue by CeliaCottle** [oscar-stack/oscar#3]
This happens even when I hadn't previously downloaded the box:

<pre>
[master] VM already created. Booting if it's not already running...
[master] Clearing any previously set forwarded ports...
[master] Forwarding ports...
[master] -- 22 => 2222 (adapter 1)
[master] -- 443 => 20443 (adapter 1)
[master] Creating shared folders metadata...
[master] Clearing any previously set network interfaces...
There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.

Here's the full log output:
VAGRANT_LOG=INFO vagrant up master
 INFO vagrant: `vagrant` invoked: ["up", "master"]
 INFO environment: Environment initialized (#<Vagrant::Environment:0x109059cb8>)
 INFO environment:   - cwd: /Users/celia/instapants
 INFO environment: Home path: /Users/celia/.vagrant.d
 INFO environment: Loading configuration...
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
 INFO cli: CLI: [] "up" ["master"]
 INFO datastore: Created: /Users/celia/instapants/.vagrant
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "--version"]
 INFO virtualbox: Using VirtualBox driver: Vagrant::Driver::VirtualBox_4_0
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee"]
 INFO vm: Loading guest: linux
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "--version"]
 INFO virtualbox: Using VirtualBox driver: Vagrant::Driver::VirtualBox_4_0
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO vm: Loading guest: linux
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--machinereadable"]
 INFO up: Booting: master
 INFO interface: info: VM already created. Booting if it's not already running...
[master] VM already created. Booting if it's not already running...
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--machinereadable"]
 INFO hosts: Host class: Vagrant::Hosts::BSD
 INFO runner: Running action: start
 INFO warden: Calling action: #<Vagrant::Action::General::Validate:0x10931dfd0>
 INFO warden: Calling action: #<Vagrant::Action::VM::CheckAccessible:0x10931df80>
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--machinereadable"]
 INFO warden: Calling action: #<Vagrant::Action::VM::CleanMachineFolder:0x10931df30>
 INFO subprocess: Starting process: ["VBoxManage", "list", "systemproperties"]
 INFO warden: Calling action: #<Vagrant::Action::VM::ClearForwardedPorts:0x10931dee0>
 INFO interface: info: Clearing any previously set forwarded ports...
[master] Clearing any previously set forwarded ports...
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "modifyvm", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--natpf1", "delete", "dr-jur", "--natpf1", "delete", "ssh"]
 INFO warden: Calling action: #<Vagrant::Action::Env::Set:0x10931de90>
 INFO warden: Calling action: #<Vagrant::Action::VM::CheckPortCollisions:0x10931de40>
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "list", "vms"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "e933f840-6896-4e26-b713-c200403b2684", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "def3f785-b1d9-49ac-931d-65b86c9e616c", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "d0535fe7-ca42-4dcf-8fdf-8b7c39b65447", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "edf79f31-7f57-4a07-917e-87cb77c6ea5a", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "8519a929-963d-4eae-8556-901ed27ea9d1", "--machinereadable"]
 INFO warden: Calling action: #<Vagrant::Action::VM::ForwardPorts:0x10931ddf0>
 INFO interface: info: Forwarding ports...
[master] Forwarding ports...
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--machinereadable"]
 INFO interface: info: -- 22 => 2222 (adapter 1)
[master] -- 22 => 2222 (adapter 1)
 INFO interface: info: -- 443 => 20443 (adapter 1)
[master] -- 443 => 20443 (adapter 1)
 INFO subprocess: Starting process: ["VBoxManage", "modifyvm", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--natpf1", "ssh,tcp,,2222,,22", "--natpf1", "dr-jur,tcp,,20443,,443"]
 INFO warden: Calling action: #<Vagrant::Action::VM::Provision:0x10931dda0>
 INFO warden: Calling action: #<Vagrant::Action::VM::PruneNFSExports:0x10931db98>
 INFO subprocess: Starting process: ["VBoxManage", "list", "vms"]
 INFO warden: Calling action: #<Vagrant::Action::VM::NFS:0x109314d18>
 INFO warden: Calling action: #<Vagrant::Action::VM::ClearSharedFolders:0x1093109c0>
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "sharedfolder", "remove", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--name", "v-root"]
 INFO subprocess: Starting process: ["VBoxManage", "sharedfolder", "remove", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--name", "manifests"]
 INFO subprocess: Starting process: ["VBoxManage", "sharedfolder", "remove", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--name", "modules"]
 INFO warden: Calling action: #<Vagrant::Action::VM::ShareFolders:0x1093035e0>
 INFO interface: info: Creating shared folders metadata...
[master] Creating shared folders metadata...
 INFO subprocess: Starting process: ["VBoxManage", "sharedfolder", "add", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--name", "v-root", "--hostpath", "/Users/celia/instapants"]
 INFO subprocess: Starting process: ["VBoxManage", "sharedfolder", "add", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--name", "manifests", "--hostpath", "/Users/celia/instapants/manifests"]
 INFO subprocess: Starting process: ["VBoxManage", "sharedfolder", "add", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--name", "modules", "--hostpath", "/Users/celia/instapants/modules"]
 INFO warden: Calling action: #<Vagrant::Action::VM::HostName:0x109303568>
 INFO warden: Calling action: #<Vagrant::Action::VM::ClearNetworkInterfaces:0x1092fc6c8>
 INFO interface: info: Clearing any previously set network interfaces...
[master] Clearing any previously set network interfaces...
 INFO subprocess: Starting process: ["VBoxManage", "modifyvm", "ca95d645-d8ec-4c8f-ba26-4c073f4c55ee", "--nic2", "none", "--nic3", "none", "--nic4", "none", "--nic5", "none", "--nic6", "none", "--nic7", "none", "--nic8", "none"]
 INFO warden: Calling action: #<Vagrant::Action::VM::Network:0x1092f6430>
 INFO subprocess: Starting process: ["VBoxManage", "list", "bridgedifs"]
 INFO subprocess: Starting process: ["VBoxManage", "list", "dhcpservers"]
 INFO subprocess: Starting process: ["VBoxManage", "list", "hostonlyifs"]
 INFO subprocess: Starting process: ["VBoxManage", "hostonlyif", "create"]
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VBoxManageError: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.>
ERROR vagrant: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR vagrant: /Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/driver/virtualbox_base.rb:261:in `execute'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/driver/virtualbox_4_0.rb:44:in `create_host_only_network'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/network.rb:276:in `create_hostonly_network'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/network.rb:230:in `hostonly_adapter'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/network.rb:36:in `send'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/network.rb:36:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/network.rb:31:in `each'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/network.rb:31:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/clear_network_interfaces.rb:26:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/host_name.rb:10:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/share_folders.rb:20:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/clear_shared_folders.rb:13:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/nfs.rb:40:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/prune_nfs_exports.rb:15:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/provision.rb:29:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/forward_ports.rb:24:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/check_port_collisions.rb:38:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/env/set.rb:16:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/clear_forwarded_ports.rb:13:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/clean_machine_folder.rb:17:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/general/validate.rb:14:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/warden.rb:33:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/builder.rb:92:in `call'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/runner.rb:49:in `run'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/util/busy.rb:19:in `busy'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/action/runner.rb:49:in `run'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/vm.rb:192:in `run_action'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/vm.rb:150:in `start'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/command/up.rb:43:in `execute'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/command/base.rb:100:in `with_target_vms'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/command/base.rb:95:in `each'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/command/base.rb:95:in `with_target_vms'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/command/up.rb:39:in `execute'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/cli.rb:38:in `execute'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/lib/vagrant/environment.rb:156:in `cli'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/gems/vagrant-0.9.7/bin/vagrant:43
/Users/celia/.rvm/gems/ruby-1.8.7-p357/bin/vagrant:19:in `load'
/Users/celia/.rvm/gems/ruby-1.8.7-p357/bin/vagrant:19
 INFO interface: error: There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
There was an error executing the following command with VBoxManage:

["hostonlyif", "create"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.

</pre>

**Comment by JulianVolodia** [comment]
On Linux say:

`sudo modprobe vboxnetadp`

**Comment by JulianVolodia** [comment]
when have trouble  with 

`vboxnet*`
then reboot and:
`sudo /etc/init.d/vboxdrv setup`
