### ISSUE TITLE
PuppetEnterprise install failing - what should be the correct cert name???

### ISSUE THREAD

**Issue by michaelokoluko** [oscar-stack/oscar#43]
Hi there,

Tried another Puppet master install on Ubuntu 12.04 LTS ad get the same error after the “waiting for node classifier….” – see embedded error below. I used the public IP for the certificate name which seems to break it but if I use the Private IP if doesn’t fail but the agent can’t connect to the private IP just the Public but the agents checks-in into the console screen listing its Finger print but never gets listed and on checking event viewer I see the error message “cert doesn’t match” as it was expecting a matching cert from the private IP – I don’t get it,  Any pointers ?

```
?? The puppet master's certificate will contain a unique name ("certname");
   this should be the main DNS name at which it can be reliably reached.
   Puppet master's certname? [Default:ip-172-31-X-X.eu-west-1.compute.internal] ec2-54-77-X-X.eu-west-1.compute.amazonaws.com

?? The puppet master's certificate can contain DNS aliases; agent nodes will
   only trust the master if they reach it at its certname or one of these
   official aliases. Puppet master's DNS aliases (comma-separated list)?
   [Default:ec2-54-77-X-X,ec2-54-77-X-X.eu-west-1.compute.amazonaws.com,puppet,pupp                                                                                                                                                             et.eu-west-1.compute.amazonaws.com]


ERRor!!!!!

Waiting for Node Classifier to start...
!!! WARNING: The node classifier could not be reached; please check the logs in '/var/log/puppetlabs/console-services/' for more information.
/opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "ec2-54-77-X-X.eu-west-1.compute.amazonaws.com" port 4433 (Errno::ECONNREFUSED)
        from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:879:in `open'
        from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
        from /opt/puppetlabs/puppet/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:878:in `connect'
        from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:1375:in `request'
        from /tmp/puppet-enterprise-2015.2.0-ubuntu-12.04-amd64/update-superuser-password.rb:51:in `get_response'
        from /tmp/puppet-enterprise-2015.2.0-ubuntu-12.04-amd64/update-superuser-password.rb:96:in `get_user'
        from /tmp/puppet-enterprise-2015.2.0-ubuntu-12.04-amd64/update-superuser-password.rb:104:in `main'
        from /tmp/puppet-enterprise-2015.2.0-ubuntu-12.04-amd64/update-superuser-password.rb:108:in `<main>'

--------------------------------------------------------------------------------

STEP 5: DONE

Thanks for installing Puppet Enterprise!

   To learn more and get started using Puppet Enterprise, refer to the
   Puppet Enterprise Quick Start Guide
   (http://docs.puppetlabs.com/pe/latest/quick_start.html) and the Puppet
   Enterprise Deployment Guide
   (http://docs.puppetlabs.com/guides/deployment_guide/index.html).

   The console can be reached at the following URI:
    *  https://ip-172-31-X-X.eu-west-1.compute.internal:3000

================================================================================

## NOTES

   Puppet Enterprise has been installed to "/opt/puppetlabs," and its
   configuration files are located in "/etc/puppetlabs".

   Answers from this session saved to
   '/tmp/puppet-enterprise-2015.2.0-ubuntu-12.04-amd64/answers.lastrun.ip-172-31-X-X.eu-west-1.compute.internal'
   In addition, auto-generated database users and passwords have been saved
   to '/etc/puppetlabs/installer/database_info.install'
   !!! WARNING: Do not discard these files! All auto-generated database
   users and passwords have been saved in them. You will need this
   information to configure the console role during installation.

   If you have a firewall running, please ensure the following TCP ports are
   open: 3000, 4433, 8140, 61613

   !!! WARNING: Installer failed to classify Puppet Enterprise. Puppet
   Enterprise will not be able to manage itself because of this. Check
   '/var/log/puppetlabs/console-services/' for more information.

   !!! WARNING: Installer failed to update superuser password. This leaves
   your PE installation at risk. Check
   '/var/log/puppetlabs/console-services/' for more information. Log into
   the console (user: admin, password: admin) as soon as possible and change
   the admin users password through the console.

--------------------------------------------------------------------------------

root@ip-172-31-X-X:/tmp/puppet-enterprise-2015.2.0-ubuntu-12.04-amd64#


```

**Comment by adrienthebo** [comment]
The installer ran into an error while trying to contact ec2-54-77-X-X.eu-west-1.compute.amazonaws.com, what is that machine doing and is port 4433 firewalled off when it shouldn't be?

**Comment by michaelokoluko** [comment]
Hello Adrien,



Thanks for getting back to me.



All looks good J



Basically I created a masters answers file( mastersanswer.install) edited
all the required IP fields (cert, dns, puppetdb e.t.c) in the dns field I
*deleted* all the defaults puppet, puppet.amazonaws.com.., ip-172-16-X-X
etc. and pointed them to the public IP
ec2-54-77-x-x.eu-west-1.compute.amazonaws.com
<http://ec2-52-16-x-x.eu-west-1.compute.amazonaws.com> and it installed
without any issues and then when installing the agent on windows pointed
the FQDN to the puppet master by using
ec2-54-77-x-x.eu-west-1.compute.amazonaws.com
<http://ec2-52-16-x-x.eu-west-1.compute.amazonaws.com>. All 3 windows 2012
agent checked in to get their certs signed and accepted and within 7 – 8
mins I could see all 3 listed in the console screen J





Now I can start some testing…



BTW: Do you have any pointers on how to deploy and execute a
PowerShell/JSON script on the master in a view to apply to all 3 windows
agents either via the puppet master command line or via the Management
console or both if possible – I believe I need a manifest running the exec
command is that right?



Many thanks in advance.


Michael

**Comment by michaelokoluko** [comment]
Hi Adrien,



Hope you are well.



Thanks for your help with the initial setting up of my puppet master/agent
environment.



Quick question, where can I get a manifest or concise guidance on the best
way to deploy and execute a PowerShell script (rebuilds a windows server) onto
my windows server using my puppet master ?



I have checked with community and the ask link but haven’t got any response
or tangible answer



If I can achieve this feat it would be the  icing on the cake for our
evaluation of Puppet.



Many thanks in advance for your assistance

**Comment by adrienthebo** [comment]
If you want to copy a powershell script to your agents, you'll need a module that contains that script, and a manifest that contains the necessary resources to copy that script to the agents and then run it.

So something like this:

```
.
└── my_powershell_script
    ├── files
    │   └── my_script.ps1
    └── manifests
        └── init.pp
```

That init.pp will have contents like this:

```
class my_powershell_script {
  file { "c:\\my_script.ps1":
    ensure => present,
    source => "puppet:///modules/my_powershell_script/my_script.ps1",
  }

  exec { "c:\\my_script.ps1":
    # If you want this to only run under certain conditions, use the `unless` or `onlyif` params
    require => File["c:\\my_script.ps1"],
  }
}
```

Since it looks like you've resolved the issue with installing PE with vagrant-pe_build, I'm going to close out this ticket. If you have additional questions about how to run powershell scripts with Puppet, check out the mailing list (https://groups.google.com/forum/#!forum/puppet-users), question board (http://ask.puppetlabs.com/questions/), or IRC channel (http://irc.lc/freenode/puppet).

**Comment by michaelokoluko** [comment]
Hi Adrien,



Many thanks for the tips J





Being that I’m a bit of a puppet virgin, I suspect somewhere in the
manifest code I’ll require the use of the resource “command”, “provider =>
PowerShell” - I believe under the exec code bit and do I just require
an “init.pp”
or other .pp files - assuming the code needs to be split…reason being that
the current manual steps you to basically do the below



1.       Port this PowerShell script (download.ps1) from the master to the
windows hosts *(the new puppet process to be implemented by the below code)*

2.       Execute the command – tantamount to double clicking the .ps1
script – this is the current manual process hence we want to use
puppet *(manual
at the moment)*

3.       When code has been run there is a stage where you get a prompt to
“hit any key to continue” which at that point the scripts completes and the
popped-up dialog cmd/ps1 dialog box disappears – do you require a logout
resources at this stage *(?)*





4.       Also at some stage in the above process you get a prompt to enter
the environment you are deploying this windows build to i.e. TEST,
DEV or  LIVE
at the moment the scripts reads an external text file and then continues
(this can be ignored for now as this only happens in the TEST build and not
in the DEV or LIVE build



Sorry to be a pain but this is an interesting challenge and working in an
exciting environment – working in a Video gaming company. For what it’s
worth I might look to attend a Puppet training course here in London -UK.
At the moment I use Linux Academy videos and a PDF book called Pro Puppet
second edition by James Turnbull, Spencer Krum, Ben Kero and 2 others.



The issue I find is there are a few overlapping attribute like File/path or
command/ensure how can one safely decipher the correct one to use – I guess
it depends on user preference or the context, scenario or use case – it can
get a bit tricky.



Finally someone from Puppetlabs yesterday sent me this below snippet about  DSC
and a just newly release PowerShell module.



*“**"Our goal is to give everyone the power to use the best tools to manage
their infrastructure, whether it's Linux, Windows, or something else," said
Nigel Kersten, CIO, Puppet Labs. "By adding DSC and Windows Server Update
Service support we're making it easier for teams managing diverse
infrastructure to embrace DevOps practices by providing a common language
and workflow to automate all aspects of the system regardless of the
underlying platform.”*



Would that be usefull?



Ever used or heard about chocholatey and windows?

**Comment by Sharpie** [comment]
@michaelokoluko These are all good questions, but way out of scope for the issue tracker of the Oscar project. These are much better posed in the community forums that Adrien referenced:

  - the mailing list (https://groups.google.com/forum/#!forum/puppet-users)
  - The Ask site (http://ask.puppetlabs.com/questions/)
  - And the IRC channel (http://irc.lc/freenode/puppet)

There you'll be able to find answers from a wide variety of Puppet users. Be aware that certain questions, such as automating installers with PowerShell, would be better posed to a PowerShell user group. Puppet can execute such a script, once written. However, the creation of these scripts is a separate topic from Puppet usage.

**Comment by michaelokoluko** [comment]
Hi Adrien

I have made some progress and almost seeing the light at the end of the
tunnel but I'm getting an error and no feedback from the "Ask Questions
resource"

Following on from the above issue I have now amended my code and run a
puppet parser validation on the init.pp and no syntax errors...

however when I run a puppet agent --noop -t on the windows node I get the
below error

"'Failed to apply catalog: Parameter creates failed on Exec[create
repo_dir]: creates must be a fully qualified path at
/opt/puppetlabs/puppet/modules/pe_repo/manifests/init.pp:30"

Below is my current init.pp manifest - any ideas where I have gone off
tangent - I believe the attributes and parameters may not be in the right
order

class downloadScript {
  file { "c:\\downdownload.ps1":
    ensure => present,
    #source => "puppet:///modules/downloadScript/download.ps1",
    source  => "c:\\downdownload.ps1"
  }
  exec {"c:\\download.ps1":
    # if you want this to only run under certain conditions, use the
'unless' or 'onlyif'
    creates     => "puppet:///modules/downloadScript/download.ps1",
    require     => File["c:\\downdownload.ps1"],
    refreshonly => true,
    notify      => "puppet:///modules/downloadScript/download.ps1",
    logoutput   => true,
    provider    => powershell,
    subscribe   =>
'C:/WINDOWS/Sytems32/WindowsPowerShell/v1.0/powershell.exe'
    }
}

**Comment by Sharpie** [comment]
> I have made some progress and almost seeing the light at the end of the
tunnel but I'm getting an error and no feedback from the "Ask Questions
resource"

The Ask site is very much suited to gathering the best answer for single questions. Your post contains a list of 6 questions, which makes it very difficult for a contributor to craft a nicely focused answer. Community members also tend to avoid questions that start with "Urgent!!!" or "Help!!!" as many visit the forums during their downtime when they want to get away from the urgent issues of the world.

I've posted a response to your main question on Ask --- hopefully that will be helpful. However, this discussion is still wildly off topic for the Oscar bugtracker, so I'm closing the thread here.
