### ISSUE TITLE
More memory by default...

### ISSUE THREAD

**Issue by TJM** [oscar-stack/oscar#49]
It would seem the default role sets up 1024M of ram for the puppet master, which is not enough. The installer fails, at least on CentOS 7.2. I suggest bumping that up to a more reasonable number for the default.

And... while you are at it, it would appear that it doesn't prefer "provider:" anymore:

```
WARN config_builder: The provider attribute, set on vm master, is deprecated and will be removed in an upcoming release. Use the providers attribute instead.
```

... which might simplify your templates?

Tommy

**Comment by Sharpie** [comment]
Just shipped Oscar 0.5.0 which contains this change in addition to some other template updates.
