### ISSUE TITLE
fqdn not listed in /etc/hosts

### ISSUE THREAD

**Issue by terrimonster** [oscar-stack/oscar#54]
The fqdn is not being associated with the IP in /etc/hosts during provisioning. This is resulting in errors in installing the master:

2017-04-07 17:39:08,563 - [Error]: Failed to apply catalog: Could not connect to the Node Manager service at https://master.example.com:4433/classifier-api: #<SocketError: getaddrinfo: Name or service not known>

Using auto_network: true in roles.yaml

Using oscar 0.5.3. Tried downgrading to 0.5.2, same result.

**Comment by Sharpie** [comment]
Hmm. What was the YAML config for `master.example.com`?

**Comment by Sharpie** [comment]
Also, which Vagrant version? I've heard rumors of AutoNetwork issues on 1.9.x, but I've been stuck on 1.8.7 for a while.

**Comment by terrimonster** [comment]
YAML config:

roles:
  pe-puppet-master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    providers:
      - type: virtualbox
        linked_clone: true
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 2048]
    provisioners:
      - {type: hosts, sync_hosts: true}
      - {type: shell, inline: 'sh /vagrant/provision/proxy.sh'}
      - {type: shell, path: 'provision/set_env.sh'}
      - {type: pe_bootstrap, role: !ruby/sym master}

----

Vagrant 1.9.3

With the above config, everything is fine if I install PE 2015.3.3. If I install 2016.4.3, I get the socket error.

**Comment by terrimonster** [comment]
I had been using vagrant 1.8.7, same issue. I upgraded to 1.9.3 to see if that helped.

**Comment by Sharpie** [comment]
Hmm. I would expect the `{type: hosts, sync_hosts: true}` provisioner to be adding an entry for the fqdn. Is the `hostname:` on the VM definition being set to `master.example.com`?

Is there any difference if the following provisioner configuration is used?

```
- type: hosts
  sync_hosts: true
  hosts:
    - ['@vagrant_private_networks', ['@vagrant_hostnames']]
    
```

**Comment by terrimonster** [comment]
Hrm. Ok, using that provisioner configuration, now the hostname is in /etc/hosts associated with the IP address. BUT, I'm still getting the error:

 [Error]: Failed to apply catalog: Could not connect to the Node Manager service at https://master.example.com:4433/classifier-api: #<SocketError: getaddrinfo: Name or service not known>

**Comment by terrimonster** [comment]
Ah ha, so I fixed this by throwing in the fqdn of the master in the hostnames array.

I'm closing this, as the fix was to RTFM when the gem was updated.

Thank you for your time, Sharpie :)
